# Generated by Django 6.0.5 on 2026-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('press_banca', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sentadilla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peso_muerto', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiaEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('musculos1', models.CharField(max_length=30)),
                ('musculos2', models.CharField(max_length=30)),
                ('musculos3', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='registropeso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registropeso',
            name='valor',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
