# Generated by Django 5.2.14 on 2026-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registrobasicos_registrodiaejercicios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiaGimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('musculo1', models.CharField(max_length=30)),
                ('musculo2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEjerciciosBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_banca', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peso_muerto', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sentadilla', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroBasicos',
        ),
        migrations.DeleteModel(
            name='RegistroDiaEjercicios',
        ),
        migrations.AlterField(
            model_name='registropeso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
