# Generated by Django 5.2.14 on 2026-05-21 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_registrodiagimnasio_registroejerciciosbasicos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodiagimnasio',
            old_name='musculo1',
            new_name='musculos1',
        ),
        migrations.RenameField(
            model_name='registrodiagimnasio',
            old_name='musculo2',
            new_name='musculos2',
        ),
        migrations.AddField(
            model_name='registrodiagimnasio',
            name='musculos3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registroejerciciosbasicos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodiagimnasio',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registropeso',
            name='fecha',
            field=models.DateField(),
        ),
    ]
